# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - delta_controller

  delta_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - arm_1_delta_joint
      - arm_2_delta_joint
      - arm_3_delta_joint
    action_ns: follow_joint_trajectory
    default: true