# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    delta_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

delta_controller:
  ros__parameters:
    joints:
      - arm_1_delta_joint
      - arm_2_delta_joint
      - arm_3_delta_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity